### PR TITLE
Fixed problem in older devices and Fixed crash of nuget manager;

### PR DESCRIPTION
**Pull request by guilherme-mantovani**
Fixed problem in older devices and Fixed crash of nuget manager;

### CODE REVIEW

**Comment by fvermeulen** [comment]
will look into the changes hopefully today, increase the version and build release

**Comment by fvermeulen** [comment]
@guilherme-mantovani had to open a new pr to fix that, because i can't change files, which i had to fix

but another question, why does your nuget-manager crash?
do you use mac or windows?
I looked up the xamarin forms nuspec file. It lüüks similar to our nuspec file

**Comment by guilherme-mantovani** [comment]
I use windows 10, visual studio 2015. The nuget crashes  only in the version 0.6.5, making all the nuget manager pages stop working.

**Comment by omares** [comment]
Just to link the mentioned PR: #51 

I guess the nuget crash still exists?

**Comment by guilherme-mantovani** [comment]
Now the app is working, but the nuget is still broken. I found the problem: in the nuspec file, the tag title need to be before the version tag. Thanks for the version.

**Comment by fvermeulen** [comment]
mhh the title-tag is in our current nuspec-file before the version-tag

But I will compare our nuspec with the nuspec from Xamarin forms. Maybe it is also due to the different filesystem structure

opened an issue for that. #52

Will close this here, because PR #51 solved the problem of the autofocus

**Pull request closed without merging**
